spring:
  r2dbc:
    initialization-mode: always
    schema: classpath:phone-bank.sql
    url: r2dbc:postgresql://localhost:5435/phonebank
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
seed:
  phone-data-file-path: classpath:Phone-Data.csv
  device-info-file-path: classpath:device-info.csv

logging:
  level:
    com.store.phonebank: INFO

fonoapi:
  url: https://fonoapi.freshpixl.com/v1/getdevice
  token: your_token_here