spring:
  r2dbc:
    initialization-mode: always
    schema: classpath:phone-bank.sql
    url: r2dbc:postgresql://localhost:5435/phonebank
    username: admin
    password: password
    driver-class-name: io.r2dbc:r2dbc-postgresql
  sql:
    init:
      platform: postgres
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: simple
seed:
  phone-data-file-path: classpath:Phone-Data.csv
  device-info-file-path: classpath:device-info.csv

resilience4j.circuitbreaker:
  instances:
    bookPhone:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: PT1S
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
    returnPhone:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: PT1S
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

logging:
  level:
    com.store.phonebank: DEBUG

fonoapi:
  url: https://fonoapi.freshpixl.com/v1/getdevice
  token: your_token_here


springfox:
  documentation:
    swagger-ui:
      enabled: true